// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQLrrEmFlOZUnlPydLKkQenpUs8VCnRA',
    appId: '1:758254647887:web:966ae53a90fef1d309883a',
    messagingSenderId: '758254647887',
    projectId: 'neo-card-app',
    authDomain: 'neo-card-app.firebaseapp.com',
    storageBucket: 'neo-card-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7w9rxnjGLYeGoaH6z7goHHtuS7g4k0VY',
    appId: '1:758254647887:android:f5763a6e4f2cdb1609883a',
    messagingSenderId: '758254647887',
    projectId: 'neo-card-app',
    storageBucket: 'neo-card-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwRKgMJUQQWZH0jyOcO0yjHoD6dCynO2E',
    appId: '1:758254647887:ios:27d4b67ebba48feb09883a',
    messagingSenderId: '758254647887',
    projectId: 'neo-card-app',
    storageBucket: 'neo-card-app.firebasestorage.app',
    iosBundleId: 'com.example.neoCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwRKgMJUQQWZH0jyOcO0yjHoD6dCynO2E',
    appId: '1:758254647887:ios:27d4b67ebba48feb09883a',
    messagingSenderId: '758254647887',
    projectId: 'neo-card-app',
    storageBucket: 'neo-card-app.firebasestorage.app',
    iosBundleId: 'com.example.neoCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfQLrrEmFlOZUnlPydLKkQenpUs8VCnRA',
    appId: '1:758254647887:web:d7c09a2f4cdd0b0909883a',
    messagingSenderId: '758254647887',
    projectId: 'neo-card-app',
    authDomain: 'neo-card-app.firebaseapp.com',
    storageBucket: 'neo-card-app.firebasestorage.app',
  );
}
